# Generated by Django 5.0.6 on 2024-06-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter_Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('is_input', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('concepts', models.ManyToManyField(related_name='input_concepts_set', to='Service.parameter_concept')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cost', models.FloatField()),
                ('input_concepts', models.ManyToManyField(related_name='input_services', to='Service.parameter_concept')),
                ('output_concepts', models.ManyToManyField(related_name='output_services', to='Service.parameter_concept')),
                ('type', models.ManyToManyField(related_name='services', to='Service.servicetype')),
            ],
        ),
    ]
