# Generated by Django 5.0.6 on 2024-06-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='service',
            name='input_concepts',
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=320),
        ),
        migrations.RemoveField(
            model_name='service',
            name='output_concepts',
        ),
        migrations.RemoveField(
            model_name='service',
            name='type',
        ),
        migrations.AddField(
            model_name='service',
            name='input_concepts',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='output_concepts',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(default=0, max_length=320),
            preserve_default=False,
        ),
    ]
