# Generated by Django 5.0.6 on 2024-06-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_alter_service_cost_remove_service_input_concepts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='concepts',
        ),
        migrations.DeleteModel(
            name='Parameter_Concept',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
