# Generated by Django 5.0.6 on 2024-06-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_remove_servicetype_concepts_delete_parameter_concept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='label',
            field=models.CharField(default='', max_length=320),
        ),
    ]
